### PR TITLE
Jenkins pipeline for orchestrator

### PR DESCRIPTION
**Pull request by orviz**
## Content:
++ Usual CI and metrics checks 
++ Docker image building and publication to DockerHub
++ OWASP dependency check
++ Issue creation on JIRA when new release (tag) is pushed

### CODE REVIEW

**Comment by orviz** [comment]
Based on PR #276

**Comment by alberto-brigandi** [comment]
Hi Pablo,
the docker image right now is built by this [public job](https://ci.cloud.reply.eu/jenkins/job/INDIGO/job/orchestrator-publish/) on our Jenkins, but we're planning to move it to Travis, as we did for our QA tests (I just need to find some time to write the shell script)

Is it strictly mandatory to move the Docker image building to EMT's Jenkins?

**Comment by orviz** [comment]
Hi @alberto-brigandi 
i'm afraid it is mandatory for pushing images to any INDIGO/DEEP/XDC DockerHub organizations, but this does not mean that you cannot rely on Travis to push images to any other DockerHub repository you may have.

**Comment by orviz** [comment]
merging the different PRs related to the Jenkinsfile to this one

**Comment by orviz** [comment]
Hi @alberto-brigandi @maricaantonacci (for the first time :) ), kindly reminder that we should move this forward.

**Comment by alberto-brigandi** [comment]
Hi @orviz,
apologies, I completely missed your answer.

Regarding the Docker image build, I definitely understand your point.

I saw the pipeline though and, correct me if I'm wrong, it seems to be pushing only the master branch and the git tags, and using the branch name as image tag name.

What we're doing right now with our jenkins is:
- Build an image from `master` using as tags:
  - the maven version of the orchestrator (e.g. `2.0.0-SNAPSHOT`)
  - `latest`
- Build an image from the stable branches (e.g. `releases/2-0-stable`, where all the backported fixes for the patch versions are cherry picked) using as tag the maven version of the orchestrator (e.g. `2.0.1-SNAPSHOT`)
- Build an image from the git tags using as tag the maven version of the orchestrator (e.g. `2.0.0-RC.1`, `2.0.0-FINAL`, `2.1.0-FINAL`, `2.0.1-FINAL`)
- Build an image from the PRs code using as tag the string `pr-${NUM_OF_PR}`

Do you think it'd feasible to replicate the same behavior on the EMT jenkins?

**Pull request merged**
